[build]
  # フロントエンドディレクトリをベースに設定
  base = "receipt-scanner-app/receipt-scanner-frontend"
  
  # ビルドコマンド
  command = "npm ci && npm run build"
  
  # 公開ディレクトリ（Viteのデフォルト出力先）
  publish = "dist"

[build.environment]
  # Node.js バージョン指定
  NODE_VERSION = "18"
  
  # 本番環境用API URL（GitHub Secretsから設定）
  VITE_API_URL = "https://your-backend-api-url.com"

# フロントエンド用の環境変数
[context.production.environment]
  VITE_API_URL = "https://your-production-api-url.com"

[context.deploy-preview.environment]
  VITE_API_URL = "https://your-staging-api-url.com"

# リダイレクト設定（SPA用）
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# ヘッダー設定（セキュリティ）
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://api.openai.com https://your-api-domain.com https://your-backend-api-url.com https://your-production-api-url.com https://your-staging-api-url.com https://localhost:8000"

# キャッシュ設定
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"